# Generated by Django 4.2.25 on 2025-12-18 21:54

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(help_text='Type de produit agricole (ex: Cacao, Café, Noix de cajou, etc.)', max_length=150, verbose_name='Nom de la commodité')),
                ('couleur', colorfield.fields.ColorField(default='#FF0000', help_text="Couleur pour l'affichage sur la carte", image_field=None, max_length=25, samples=None, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Commodité',
                'verbose_name_plural': 'Commodités',
                'db_table': 'commodite',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCommodite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(help_text='Type de produit agricole (ex: Cacao, Café, Noix de cajou, etc.)', max_length=150, verbose_name='Nom de la commodité')),
                ('couleur', colorfield.fields.ColorField(default='#FF0000', help_text="Couleur pour l'affichage sur la carte", image_field=None, max_length=25, samples=None, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de mise à jour')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Commodité',
                'verbose_name_plural': 'historical Commodités',
                'db_table': 'commodite_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FournisseurCommodite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_fournisseurs', to='commodites.commodite', verbose_name='Commodité')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_commodites', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Lien Fournisseur-Commodité',
                'verbose_name_plural': 'Liens Fournisseur-Commodités',
                'db_table': 'fournisseur_commodite',
            },
        ),
        migrations.AddIndex(
            model_name='commodite',
            index=models.Index(fields=['nom'], name='commodite_nom_a0243a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commodite',
            unique_together={('nom',)},
        ),
        migrations.AddIndex(
            model_name='fournisseurcommodite',
            index=models.Index(fields=['fournisseur'], name='fournisseur_fournis_590906_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseurcommodite',
            index=models.Index(fields=['commodite'], name='fournisseur_commodi_ca5afb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='fournisseurcommodite',
            unique_together={('fournisseur', 'commodite')},
        ),
    ]
