# Generated by Django 4.2.25 on 2025-10-27 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fournisseurs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("commodites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalcommodite",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="fournisseurcommodite",
            name="commodite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liens_fournisseurs",
                to="commodites.commodite",
                verbose_name="Commodité",
            ),
        ),
        migrations.AddField(
            model_name="fournisseurcommodite",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liens_commodites",
                to="fournisseurs.fournisseur",
                verbose_name="Fournisseur",
            ),
        ),
        migrations.AddIndex(
            model_name="commodite",
            index=models.Index(fields=["nom"], name="commodite_nom_a0243a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="commodite",
            unique_together={("nom",)},
        ),
        migrations.AddIndex(
            model_name="fournisseurcommodite",
            index=models.Index(
                fields=["fournisseur"], name="fournisseur_fournis_590906_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fournisseurcommodite",
            index=models.Index(
                fields=["commodite"], name="fournisseur_commodi_ca5afb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="fournisseurcommodite",
            unique_together={("fournisseur", "commodite")},
        ),
    ]
