# Generated by Django 4.2.25 on 2026-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodite',
            name='couleur',
            field=models.CharField(default='#FF0000', help_text="Couleur d'affichage pour cette commodité", max_length=7, verbose_name='Couleur'),
        ),
        migrations.AlterField(
            model_name='historicalcommodite',
            name='couleur',
            field=models.CharField(default='#FF0000', help_text="Couleur d'affichage pour cette commodité", max_length=7, verbose_name='Couleur'),
        ),
    ]
