# Generated by Django 4.2.25 on 2025-12-18 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zones', '0001_initial'),
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la localité')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude ')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie de la localité en kilomètres carrés', max_digits=15, null=True, verbose_name='Superficie (km²)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Localité',
                'verbose_name_plural': 'Localités',
                'db_table': 'localite',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la ville')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie de la ville en kilomètres carrés', max_digits=15, null=True, verbose_name='Superficie (km²)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('est_ville_reference', models.BooleanField(default=False, help_text='Cochez pour définir cette ville comme ville de référence pour sa zone', verbose_name='Ville de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('zone', models.ForeignKey(help_text='Zone géographique à laquelle appartient la ville', on_delete=django.db.models.deletion.PROTECT, related_name='villes', to='zones.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'Ville',
                'verbose_name_plural': 'Villes',
                'db_table': 'ville',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PortLocalite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance entre le port et la localité', max_digits=15, null=True, verbose_name='Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('localite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports_localites', to='villes.localite', verbose_name='Localité')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localite_ports', to='port.port', verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Lien Port-Localite',
                'verbose_name_plural': 'Liens Port-Localites',
                'db_table': 'port_localite',
            },
        ),
        migrations.AddField(
            model_name='localite',
            name='ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localites', to='villes.ville'),
        ),
        migrations.CreateModel(
            name='HistoricalVille',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(db_index=True, max_length=100, verbose_name='Nom de la ville')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie de la ville en kilomètres carrés', max_digits=15, null=True, verbose_name='Superficie (km²)')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude ')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('est_ville_reference', models.BooleanField(default=False, help_text='Cochez pour définir cette ville comme ville de référence pour sa zone', verbose_name='Ville de référence')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de mise à jour')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, db_constraint=False, help_text='Zone géographique à laquelle appartient la ville', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='zones.zone', verbose_name='Zone')),
            ],
            options={
                'verbose_name': 'historical Ville',
                'verbose_name_plural': 'historical Villes',
                'db_table': 'ville_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLocalite',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(db_index=True, max_length=100, verbose_name='Nom de la localité')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude ')),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, help_text='Superficie de la localité en kilomètres carrés', max_digits=15, null=True, verbose_name='Superficie (km²)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de mise à jour')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ville', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='villes.ville')),
            ],
            options={
                'verbose_name': 'historical Localité',
                'verbose_name_plural': 'historical Localités',
                'db_table': 'localite_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='VillePort',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance entre le port et la ville', max_digits=15, null=True, verbose_name='Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ville_ports', to='port.port', verbose_name='Port')),
                ('ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports_villes', to='villes.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Lien Ville-Port',
                'verbose_name_plural': 'Liens Ville-Ports',
                'db_table': 'ville_port',
                'indexes': [models.Index(fields=['ville'], name='ville_port_ville_i_185263_idx'), models.Index(fields=['port'], name='ville_port_port_id_9d1c3b_idx')],
                'unique_together': {('ville', 'port')},
            },
        ),
        migrations.AddIndex(
            model_name='ville',
            index=models.Index(fields=['est_ville_reference', 'zone'], name='ville_est_vil_5c7b01_idx'),
        ),
        migrations.AddIndex(
            model_name='portlocalite',
            index=models.Index(fields=['port'], name='port_locali_port_id_c0ca23_idx'),
        ),
        migrations.AddIndex(
            model_name='portlocalite',
            index=models.Index(fields=['localite'], name='port_locali_localit_f787db_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portlocalite',
            unique_together={('port', 'localite')},
        ),
        migrations.AddIndex(
            model_name='localite',
            index=models.Index(fields=['ville'], name='localite_ville_i_3c4b29_idx'),
        ),
    ]
