# Generated by Django 4.2.25 on 2025-10-17 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalVille",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Nom de la ville"
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Superficie de la ville en kilomètres carrés",
                        max_digits=15,
                        null=True,
                        verbose_name="Superficie (km²)",
                    ),
                ),
                (
                    "distance_port_abidjan",
                    models.TextField(
                        blank=True,
                        help_text="Distance entre la ville et le port d'Abidjan",
                        null=True,
                        verbose_name="Distance du port d'Abidjan",
                    ),
                ),
                (
                    "distance_port_sanpedro",
                    models.TextField(
                        blank=True,
                        help_text="Distance entre la ville et le port de San-Pedro",
                        null=True,
                        verbose_name="Distance du port de San-Pedro",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "est_ville_reference",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez pour définir cette ville comme ville de référence pour sa zone",
                        verbose_name="Ville de référence",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Zone géographique à laquelle appartient la ville",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="zones.zone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ville",
                "verbose_name_plural": "historical Villes",
                "db_table": "ville_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Ville",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nom de la ville"
                    ),
                ),
                (
                    "superficie",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Superficie de la ville en kilomètres carrés",
                        max_digits=15,
                        null=True,
                        verbose_name="Superficie (km²)",
                    ),
                ),
                (
                    "distance_port_abidjan",
                    models.TextField(
                        blank=True,
                        help_text="Distance entre la ville et le port d'Abidjan",
                        null=True,
                        verbose_name="Distance du port d'Abidjan",
                    ),
                ),
                (
                    "distance_port_sanpedro",
                    models.TextField(
                        blank=True,
                        help_text="Distance entre la ville et le port de San-Pedro",
                        null=True,
                        verbose_name="Distance du port de San-Pedro",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "est_ville_reference",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez pour définir cette ville comme ville de référence pour sa zone",
                        verbose_name="Ville de référence",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        help_text="Zone géographique à laquelle appartient la ville",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="villes",
                        to="zones.zone",
                        verbose_name="Zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ville",
                "verbose_name_plural": "Villes",
                "db_table": "ville",
                "ordering": ["nom"],
                "indexes": [
                    models.Index(
                        fields=["est_ville_reference", "zone"],
                        name="ville_est_vil_5c7b01_idx",
                    )
                ],
            },
        ),
    ]
