# Generated by Django 4.2.25 on 2025-10-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalville",
            name="distance_port_abidjan",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance entre la ville et le port d'Abidjan",
                max_digits=15,
                null=True,
                verbose_name="Distance du port d'Abidjan",
            ),
        ),
        migrations.AddField(
            model_name="historicalville",
            name="distance_port_sanpedro",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance entre la ville et le port de San-Pedro",
                max_digits=15,
                null=True,
                verbose_name="Distance du port de San-Pedro",
            ),
        ),
        migrations.AddField(
            model_name="ville",
            name="distance_port_abidjan",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance entre la ville et le port d'Abidjan",
                max_digits=15,
                null=True,
                verbose_name="Distance du port d'Abidjan",
            ),
        ),
        migrations.AddField(
            model_name="ville",
            name="distance_port_sanpedro",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance entre la ville et le port de San-Pedro",
                max_digits=15,
                null=True,
                verbose_name="Distance du port de San-Pedro",
            ),
        ),
    ]
