# Generated by Django 4.2.25 on 2025-11-04 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("villes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalville",
            name="distance_port_abidjan",
        ),
        migrations.RemoveField(
            model_name="historicalville",
            name="distance_port_sanpedro",
        ),
        migrations.RemoveField(
            model_name="ville",
            name="distance_port_abidjan",
        ),
        migrations.RemoveField(
            model_name="ville",
            name="distance_port_sanpedro",
        ),
    ]
