# Generated by Django 4.2.25 on 2025-11-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villes", "0002_remove_historicalville_distance_port_abidjan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalville",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude "),
        ),
        migrations.AddField(
            model_name="historicalville",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude "),
        ),
        migrations.AddField(
            model_name="ville",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude "),
        ),
        migrations.AddField(
            model_name="ville",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude "),
        ),
    ]
