# Generated by Django 4.2.25 on 2025-10-27 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("villes", "0002_historicalville_distance_port_abidjan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallocalite",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="villes.ville",
            ),
        ),
        migrations.AlterField(
            model_name="localite",
            name="ville",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="localites",
                to="villes.ville",
            ),
        ),
    ]
