# Generated by Django 4.2.25 on 2025-11-06 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("port", "0002_fournisseurport_distance"),
        ("villes", "0003_historicalville_latitude_historicalville_longitude_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicallocalite",
            name="distance_port_abidjan",
        ),
        migrations.RemoveField(
            model_name="historicallocalite",
            name="distance_port_sanpedro",
        ),
        migrations.RemoveField(
            model_name="localite",
            name="distance_port_abidjan",
        ),
        migrations.RemoveField(
            model_name="localite",
            name="distance_port_sanpedro",
        ),
        migrations.AddField(
            model_name="historicallocalite",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude "),
        ),
        migrations.AddField(
            model_name="historicallocalite",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude "),
        ),
        migrations.AddField(
            model_name="localite",
            name="latitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Latitude "),
        ),
        migrations.AddField(
            model_name="localite",
            name="longitude",
            field=models.FloatField(blank=True, null=True, verbose_name="Longitude "),
        ),
        migrations.CreateModel(
            name="VillePort",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance entre le port et la ville",
                        max_digits=15,
                        null=True,
                        verbose_name="Distance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ville_ports",
                        to="port.port",
                        verbose_name="Port",
                    ),
                ),
                (
                    "ville",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports_villes",
                        to="villes.ville",
                        verbose_name="Ville",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Ville-Port",
                "verbose_name_plural": "Liens Ville-Ports",
                "db_table": "ville_port",
                "indexes": [
                    models.Index(
                        fields=["ville"], name="ville_port_ville_i_185263_idx"
                    ),
                    models.Index(fields=["port"], name="ville_port_port_id_9d1c3b_idx"),
                ],
                "unique_together": {("ville", "port")},
            },
        ),
        migrations.CreateModel(
            name="PortLocalite",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distance entre le port et la localité",
                        max_digits=15,
                        null=True,
                        verbose_name="Distance",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "localite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ports_localites",
                        to="villes.localite",
                        verbose_name="Localité",
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="localite_ports",
                        to="port.port",
                        verbose_name="Port",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Port-Localite",
                "verbose_name_plural": "Liens Port-Localites",
                "db_table": "port_localite",
                "indexes": [
                    models.Index(
                        fields=["port"], name="port_locali_port_id_c0ca23_idx"
                    ),
                    models.Index(
                        fields=["localite"], name="port_locali_localit_f787db_idx"
                    ),
                ],
                "unique_together": {("port", "localite")},
            },
        ),
    ]
