# Generated by Django 4.2.25 on 2025-11-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("villes", "0004_remove_historicallocalite_distance_port_abidjan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallocalite",
            name="superficie",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Superficie de la localité en kilomètres carrés",
                max_digits=15,
                null=True,
                verbose_name="Superficie (km²)",
            ),
        ),
        migrations.AddField(
            model_name="localite",
            name="superficie",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Superficie de la localité en kilomètres carrés",
                max_digits=15,
                null=True,
                verbose_name="Superficie (km²)",
            ),
        ),
    ]
