# Generated by Django 4.2.25 on 2025-11-03 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Pays", "0002_initial"),
        ("fournisseurs", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Port",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nom du port"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude "),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude "),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Pays.pays",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port",
                "verbose_name_plural": "Ports",
                "db_table": "port",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPort",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Nom du port"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude "),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude "),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pays",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="Pays.pays",
                        verbose_name="Pays",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Port",
                "verbose_name_plural": "historical Ports",
                "db_table": "port_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FournisseurPort",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_fournisseurs",
                        to="fournisseurs.fournisseur",
                        verbose_name="Fournisseur",
                    ),
                ),
                (
                    "port",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_ports",
                        to="port.port",
                        verbose_name="Port",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lien Fournisseur-Port",
                "verbose_name_plural": "Liens Fournisseur-Ports",
                "db_table": "fournisseur_port",
                "indexes": [
                    models.Index(
                        fields=["fournisseur"], name="fournisseur_fournis_8705e3_idx"
                    ),
                    models.Index(
                        fields=["port"], name="fournisseur_port_id_30519b_idx"
                    ),
                ],
                "unique_together": {("fournisseur", "port")},
            },
        ),
    ]
