# Generated by Django 4.2.25 on 2025-11-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("port", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fournisseurport",
            name="distance",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Distance entre le port et le fournisseur",
                max_digits=15,
                null=True,
                verbose_name="Distance",
            ),
        ),
    ]
