#!/usr/bin/env python3
"""
Script to translate French strings to English in Django PO files
"""

import re
import sys

# French to English translations dictionary
TRANSLATIONS = {
    # Basic translations
    "Créé le": "Created on",
    "par": "by",
    "Partager": "Share",
    "Pays": "Country",
    "Nouveau pays": "New country",
    "Remplissez les informations du pays ci-dessous.": "Fill in the country information below.",
    "Informations de base": "Basic Information",
    "optionnel": "optional",
    "Sélectionner un fichier": "Select a file",
    "Liste des Pays": "Country List",
    "Gérez les pays disponibles dans le système": "Manage available countries in the system",
    "Ajouter un pays": "Add a country",
    "Rechercher": "Search",
    "Rechercher par nom ou code pays...": "Search by name or country code...",
    "Filtrer": "Filter",
    "Localités": "Localities",
    "Zones associées": "Associated Zones",
    "Aucune zone associée.": "No associated zone.",
    "Villes associées": "Associated Cities",
    "Aucune ville associée.": "No associated city.",
    "Localités associées": "Associated Localities",
    "Aucune localité associée.": "No associated locality.",
    "Voir le détail": "View details",
    "Supprimer": "Delete",
    "Précédent": "Previous",
    "Suivant": "Next",
    "Aucun pays trouvé": "No country found",
    "Aucun pays ne correspond à votre recherche. Essayez d'autres termes.": "No country matches your search. Try other terms.",
    
    # Common UI elements
    "Enregistrer": "Save",
    "Sauvegarder": "Save",
    "Valider": "Validate",
    "Confirmer": "Confirm",
    "Oui": "Yes",
    "Non": "No",
    "Accueil": "Home",
    "Menu": "Menu",
    "Profil": "Profile",
    "Paramètres": "Settings",
    "Déconnexion": "Logout",
    "Connexion": "Login",
    "Inscription": "Register",
    "Nom": "Name",
    "Prénom": "First Name",
    "Email": "Email",
    "Mot de passe": "Password",
    "Téléphone": "Phone",
    "Adresse": "Address",
    "Ville": "City",
    "Pays": "Country",
    "Code postal": "Postal Code",
    "Description": "Description",
    "Date": "Date",
    "Heure": "Time",
    "Prix": "Price",
    "Quantité": "Quantity",
    "Total": "Total",
    "Ajouter au panier": "Add to cart",
    "Panier": "Cart",
    "Commander": "Order",
    "Payer": "Pay",
    "Facture": "Invoice",
    "Reçu": "Receipt",
    "Expédier": "Ship",
    "Livraison": "Delivery",
    "Suivi": "Tracking",
    "Statut": "Status",
    "En attente": "Pending",
    "Confirmé": "Confirmed",
    "Expédié": "Shipped",
    "Livré": "Delivered",
    "Annulé": "Cancelled",
    "Remboursé": "Refunded",
    "Erreur": "Error",
    "Succès": "Success",
    "Information": "Information",
    "Avertissement": "Warning",
    "Attention": "Attention",
    "Chargement...": "Loading...",
    "Veuillez patienter": "Please wait",
    "Aucun résultat": "No results",
    "Aucune donnée": "No data",
    "Vide": "Empty",
    "Complété": "Completed",
    "En cours": "In progress",
    "Brouillon": "Draft",
    "Publié": "Published",
    "Privé": "Private",
    "Public": "Public",
    "Tous": "All",
    "Aucun": "None",
    "Autre": "Other",
    "Plus": "More",
    "Moins": "Less",
    "Premier": "First",
    "Dernier": "Last",
    "Suivant": "Next",
    "Précédent": "Previous",
    "Début": "Start",
    "Fin": "End",
    "Page": "Page",
    "de": "of",
    "sur": "on",
    "et": "and",
    "ou": "or",
    "avec": "with",
    "sans": "without",
    "pour": "for",
    "par": "by",
    "dans": "in",
    "à": "at",
    "le": "the",
    "la": "the",
    "les": "the",
    "un": "a",
    "une": "a",
    "des": "some",
    "ces": "these",
    "cette": "this",
    "ce": "this",
    "cela": "that",
    "ici": "here",
    "là": "there",
    "maintenant": "now",
    "avant": "before",
    "après": "after",
    "pendant": "during",
    "depuis": "since",
    "jusqu'à": "until",
    "entre": "between",
    "chez": "at",
    "vers": "towards",
    "contre": "against",
    "sous": "under",
    "sur": "on",
    "au-dessus": "above",
    "devant": "in front of",
    "derrière": "behind",
    "à côté de": "next to",
    "près de": "near",
    "loin de": "far from",
    "intérieur": "inside",
    "extérieur": "outside",
    "nord": "north",
    "sud": "south",
    "est": "east",
    "ouest": "west",
    "gauche": "left",
    "droite": "right",
    "centre": "center",
    "haut": "top",
    "bas": "bottom",
    "milieu": "middle",
    "coin": "corner",
    "bord": "edge",
    "surface": "surface",
    "profondeur": "depth",
    "largeur": "width",
    "hauteur": "height",
    "longueur": "length",
    "distance": "distance",
    "poids": "weight",
    "volume": "volume",
    "surface": "area",
    "température": "temperature",
    "pression": "pressure",
    "vitesse": "speed",
    "accélération": "acceleration",
    "force": "force",
    "énergie": "energy",
    "puissance": "power",
    "résistance": "resistance",
    "tension": "voltage",
    "courant": "current",
    "fréquence": "frequency",
    "signal": "signal",
    "donnée": "data",
    "information": "information",
    "message": "message",
    "notification": "notification",
    "alerte": "alert",
    "rappel": "reminder",
    "invitation": "invitation",
    "demande": "request",
    "réponse": "response",
    "confirmation": "confirmation",
    "autorisation": "authorization",
    "permission": "permission",
    "accès": "access",
    "connexion": "connection",
    "déconnexion": "disconnection",
    "sécurité": "security",
    "protection": "protection",
    "sauvegarde": "backup",
    "restauration": "restoration",
    "importation": "import",
    "exportation": "export",
    "téléchargement": "download",
    "téléversement": "upload",
    "synchronisation": "synchronization",
    "mise à jour": "update",
    "version": "version",
    "publication": "release",
    "beta": "beta",
    "alpha": "alpha",
    "test": "test",
    "démo": "demo",
    "exemple": "example",
    "aide": "help",
    "support": "support",
    "documentation": "documentation",
    "tutorial": "tutorial",
    "guide": "guide",
    "manuel": "manual",
    "instructions": "instructions",
    "directives": "guidelines",
    "règles": "rules",
    "conditions": "conditions",
    "termes": "terms",
    "politique": "policy",
    "confidentialité": "privacy",
    "mentions légales": "legal notices",
    "droits": "rights",
    "obligations": "obligations",
    "garantie": "warranty",
    "licence": "license",
    "copyright": "copyright",
    "marque": "trademark",
    "brevet": "patent",
    "propriété": "property",
    "propriété intellectuelle": "intellectual property",
    "contenu": "content",
    "texte": "text",
    "image": "image",
    "vidéo": "video",
    "audio": "audio",
    "fichier": "file",
    "document": "document",
    "dossier": "folder",
    "répertoire": "directory",
    "lien": "link",
    "url": "url",
    "adresse web": "web address",
    "site web": "website",
    "page web": "web page",
    "application": "application",
    "logiciel": "software",
    "programme": "program",
    "système": "system",
    "plateforme": "platform",
    "service": "service",
    "outil": "tool",
    "fonctionnalité": "feature",
    "option": "option",
    "paramètre": "parameter",
    "configuration": "configuration",
    "personnalisation": "customization",
    "adaptation": "adaptation",
    "intégration": "integration",
    "compatibilité": "compatibility",
    "performance": "performance",
    "optimisation": "optimization",
    "amélioration": "improvement",
    "évolution": "evolution",
    "développement": "development",
    "recherche": "research",
    "analyse": "analysis",
    "étude": "study",
    "rapport": "report",
    "statistique": "statistic",
    "graphique": "chart",
    "tableau": "table",
    "liste": "list",
    "formulaire": "form",
    "champ": "field",
    "case à cocher": "checkbox",
    "bouton radio": "radio button",
    "menu déroulant": "dropdown menu",
    "barre de recherche": "search bar",
    "barre de navigation": "navigation bar",
    "barre d'outils": "toolbar",
    "volet": "panel",
    "fenêtre": "window",
    "onglet": "tab",
    "bouton": "button",
    "icône": "icon",
    "symbole": "symbol",
    "logo": "logo",
    "bannière": "banner",
    "en-tête": "header",
    "pied de page": "footer",
    "menu latéral": "sidebar",
    "menu principal": "main menu",
    "menu contextuel": "context menu",
    "menu rapide": "quick menu",
    "raccourci": "shortcut",
    "touche": "key",
    "clavier": "keyboard",
    "souris": "mouse",
    "écran": "screen",
    "affichage": "display",
    "résolution": "resolution",
    "format": "format",
    "taille": "size",
    "couleur": "color",
    "style": "style",
    "thème": "theme",
    "apparence": "appearance",
    "design": "design",
    "interface": "interface",
    "expérience utilisateur": "user experience",
    "ergonomie": "ergonomics",
    "accessibilité": "accessibility",
    "facilité d'utilisation": "ease of use",
    "convivialité": "user-friendliness",
    "efficacité": "efficiency",
    "rapidité": "speed",
    "fluidité": "fluidity",
    "réactivité": "responsiveness",
    "stabilité": "stability",
    "fiabilité": "reliability",
    "disponibilité": "availability",
    "maintenance": "maintenance",
    "surveillance": "monitoring",
    "diagnostic": "diagnostic",
    "débogage": "debugging",
    "correction": "fix",
    "mise à niveau": "upgrade",
    "migration": "migration",
    "conversion": "conversion",
    "transformation": "transformation",
    "génération": "generation",
    "création": "creation",
    "modification": "modification",
    "suppression": "deletion",
    "restauration": "restoration",
    "duplication": "duplication",
    "déplacement": "move",
    "copie": "copy",
    "collage": "paste",
    "coupe": "cut",
    "sélection": "selection",
    "tri": "sort",
    "filtrage": "filtering",
    "recherche": "search",
    "remplacement": "replacement",
    "comparaison": "comparison",
    "fusion": "merge",
    "division": "split",
    "regroupement": "grouping",
    "organisation": "organization",
    "classement": "ranking",
    "catégorisation": "categorization",
    "étiquetage": "tagging",
    "annotation": "annotation",
    "commentaire": "comment",
    "note": "note",
    "rappel": "reminder",
    "tâche": "task",
    "activité": "activity",
    "processus": "process",
    "procédure": "procedure",
    "méthode": "method",
    "technique": "technique",
    "approche": "approach",
    "stratégie": "strategy",
    "plan": "plan",
    "objectif": "objective",
    "but": "goal",
    "cible": "target",
    "résultat": "result",
    "issue": "outcome",
    "conséquence": "consequence",
    "impact": "impact",
    "avantage": "advantage",
    "bénéfice": "benefit",
    "inconvénient": "disadvantage",
    "risque": "risk",
    "problème": "problem",
    "solution": "solution",
    "alternative": "alternative",
    "option": "option",
    "choix": "choice",
    "décision": "decision",
    "validation": "validation",
    "approbation": "approval",
    "rejet": "rejection",
    "acceptation": "acceptance",
    "refus": "refusal",
    "accord": "agreement",
    "contrat": "contract",
    "convention": "convention",
    "engagement": "commitment",
    "responsabilité": "responsibility",
    "obligation": "obligation",
    "devoir": "duty",
    "droit": "right",
    "liberté": "freedom",
    "égalité": "equality",
    "justice": "justice",
    "équité": "equity",
    "respect": "respect",
    "tolérance": "tolerance",
    "diversité": "diversity",
    "inclusion": "inclusion",
    "collaboration": "collaboration",
    "coopération": "cooperation",
    "partenariat": "partnership",
    "alliance": "alliance",
    "équipe": "team",
    "groupe": "group",
    "communauté": "community",
    "réseau": "network",
    "connexion": "connection",
    "lien": "link",
    "relation": "relationship",
    "interaction": "interaction",
    "communication": "communication",
    "échange": "exchange",
    "partage": "sharing",
    "transmission": "transmission",
    "réception": "reception",
    "envoi": "sending",
    "réception": "reception",
    "distribution": "distribution",
    "livraison": "delivery",
    "transport": "transport",
    "logistique": "logistics",
    "entreposage": "storage",
    "gestion": "management",
    "administration": "administration",
    "organisation": "organization",
    "planification": "planning",
    "coordination": "coordination",
    "supervision": "supervision",
    "contrôle": "control",
    "vérification": "verification",
    "audit": "audit",
    "inspection": "inspection",
    "évaluation": "evaluation",
    "appréciation": "appreciation",
    "jugement": "judgment",
    "analyse": "analysis",
    "synthèse": "synthesis",
    "résumé": "summary",
    "aperçu": "overview",
    "présentation": "presentation",
    "démonstration": "demonstration",
    "explication": "explanation",
    "description": "description",
    "définition": "definition",
    "interprétation": "interpretation",
    "compréhension": "understanding",
    "connaissance": "knowledge",
    "savoir": "knowledge",
    "compétence": "skill",
    "aptitude": "ability",
    "capacité": "capacity",
    "talent": "talent",
    "expertise": "expertise",
    "maîtrise": "mastery",
    "apprentissage": "learning",
    "formation": "training",
    "éducation": "education",
    "enseignement": "teaching",
    "instruction": "instruction",
    "orientation": "orientation",
    "conseil": "advice",
    "recommandation": "recommendation",
    "suggestion": "suggestion",
    "proposition": "proposal",
    "offre": "offer",
    "demande": "request",
    "commande": "order",
    "réservation": "reservation",
    "inscription": "registration",
    "abonnement": "subscription",
    "adhésion": "membership",
    "participation": "participation",
    "implication": "involvement",
    "engagement": "engagement",
    "contribution": "contribution",
    "investissement": "investment",
    "dépense": "expense",
    "coût": "cost",
    "prix": "price",
    "tarif": "rate",
    "budget": "budget",
    "financement": "funding",
    "subvention": "grant",
    "aide": "help",
    "assistance": "assistance",
    "support": "support",
    "accompagnement": "support",
    "guidage": "guidance",
    "encadrement": "supervision",
    "mentorat": "mentorship",
    "consultation": "consultation",
    "conseil": "advice",
    "expertise": "expertise",
    "avis": "opinion",
    "point de vue": "point of view",
    "perspective": "perspective",
    "angle": "angle",
    "approche": "approach",
    "méthodologie": "methodology",
    "technique": "technique",
    "procédé": "process",
    "opération": "operation",
    "action": "action",
    "activité": "activity",
    "tâche": "task",
    "mission": "mission",
    "mandat": "mandate",
    "fonction": "function",
    "rôle": "role",
    "position": "position",
    "poste": "position",
    "emploi": "job",
    "carrière": "career",
    "profession": "profession",
    "métier": "trade",
    "spécialité": "specialty",
    "domaine": "domain",
    "secteur": "sector",
    "branche": "branch",
    "catégorie": "category",
    "type": "type",
    "nature": "nature",
    "caractère": "character",
    "propriété": "property",
    "attribut": "attribute",
    "qualité": "quality",
    "caractéristique": "characteristic",
    "spécification": "specification",
    "critère": "criterion",
    "standard": "standard",
    "norme": "norm",
    "règle": "rule",
    "principe": "principle",
    "loi": "law",
    "réglement": "regulation",
    "directive": "directive",
    "instruction": "instruction",
    "recommandation": "recommendation",
    "ligne directrice": "guideline",
    "politique": "policy",
    "stratégie": "strategy",
    "planification": "planning",
    "programmation": "programming",
    "ordonnancement": "scheduling",
    "calendrier": "calendar",
    "agenda": "agenda",
    "horaire": "schedule",
    "timing": "timing",
    "délai": "deadline",
    "échéance": "due date",
    "période": "period",
    "durée": "duration",
    "temps": "time",
    "moment": "moment",
    "instant": "instant",
    "occasion": "occasion",
    "opportunité": "opportunity",
    "chance": "chance",
    "risque": "risk",
    "danger": "danger",
    "menace": "threat",
    "alerte": "alert",
    "avertissement": "warning",
    "notification": "notification",
    "information": "information",
    "message": "message",
    "communication": "communication",
    "annonce": "announcement",
    "déclaration": "declaration",
    "affirmation": "affirmation",
    "confirmation": "confirmation",
    "validation": "validation",
    "approbation": "approval",
    "acceptation": "acceptance",
    "accord": "agreement",
    "consentement": "consent",
    "autorisation": "authorization",
    "permission": "permission",
    "autorisation": "authorization",
    "licence": "license",
    "permis": "permit",
    "certificat": "certificate",
    "attestation": "attestation",
    "justificatif": "proof",
    "document": "document",
    "pièce": "document",
    "fichier": "file",
    "dossier": "file",
    "enregistrement": "record",
    "archive": "archive",
    "historique": "history",
    "journal": "log",
    "registre": "register",
    "liste": "list",
    "inventaire": "inventory",
    "catalogue": "catalog",
    "index": "index",
    "répertoire": "directory",
    "base de données": "database",
    "système": "system",
    "plateforme": "platform",
    "infrastructure": "infrastructure",
    "architecture": "architecture",
    "structure": "structure",
    "organisation": "organization",
    "agencement": "layout",
    "disposition": "arrangement",
    "configuration": "configuration",
    "paramétrage": "parameterization",
    "personnalisation": "customization",
    "adaptation": "adaptation",
    "modification": "modification",
    "mise à jour": "update",
    "évolution": "evolution",
    "développement": "development",
    "amélioration": "improvement",
    "optimisation": "optimization",
    "performance": "performance",
    "efficacité": "efficiency",
    "productivité": "productivity",
    "rentabilité": "profitability",
    "croissance": "growth",
    "expansion": "expansion",
    "développement": "development",
    "progrès": "progress",
    "avancement": "advancement",
    "succès": "success",
    "réussite": "achievement",
    "accomplissement": "accomplishment",
    "réalisation": "realization",
    "finalisation": "finalization",
    "achèvement": "completion",
    "terminaison": "termination",
    "fin": "end",
    "conclusion": "conclusion",
    "résultat": "result",
    "issue": "outcome",
    "conséquence": "consequence",
    "impact": "impact",
    "effet": "effect",
    "influence": "influence",
    "portée": "scope",
    "ampleur": "magnitude",
    "importance": "importance",
    "signification": "significance",
    "valeur": "value",
    "prix": "price",
    "coût": "cost",
    "dépense": "expense",
    "budget": "budget",
    "financement": "funding",
    "investissement": "investment",
    "capital": "capital",
    "ressource": "resource",
    "actif": "asset",
    "passif": "liability",
    "patrimoine": "heritage",
    "propriété": "property",
    "possession": "possession",
    "detention": "holding",
    "contrôle": "control",
    "maîtrise": "mastery",
    "gestion": "management",
    "administration": "administration",
    "direction": "management",
    "leadership": "leadership",
    "autorité": "authority",
    "pouvoir": "power",
    "influence": "influence",
    "contrôle": "control",
    "supervision": "supervision",
    "surveillance": "monitoring",
    "inspection": "inspection",
    "vérification": "verification",
    "validation": "validation",
    "certification": "certification",
    "qualification": "qualification",
    "habilitation": "authorization",
    "compétence": "competence",
    "aptitude": "aptitude",
    "capacité": "capacity",
    "habileté": "skill",
    "talent": "talent",
    "don": "gift",
    "faculté": "faculty",
    "potential": "potential",
    "possibilité": "possibility",
    "opportunité": "opportunity",
    "option": "option",
    "alternative": "alternative",
    "choix": "choice",
    "sélection": "selection",
    "décision": "decision",
    "détermination": "determination",
    "résolution": "resolution",
    "solution": "solution",
    "réponse": "answer",
    "réplique": "reply",
    "retour": "return",
    "feedback": "feedback",
    "commentaire": "comment",
    "avis": "opinion",
    "critique": "review",
    "évaluation": "evaluation",
    "appréciation": "appreciation",
    "jugement": "judgment",
    "analyse": "analysis",
    "examen": "examination",
    "étude": "study",
    "recherche": "research",
    "investigation": "investigation",
    "enquête": "survey",
    "sondage": "poll",
    "consultation": "consultation",
    "entretien": "interview",
    "discussion": "discussion",
    "débat": "debate",
    "dialogue": "dialogue",
    "conversation": "conversation",
    "échange": "exchange",
    "communication": "communication",
    "transmission": "transmission",
    "diffusion": "broadcasting",
    "distribution": "distribution",
    "partage": "sharing",
    "collaboration": "collaboration",
    "coopération": "cooperation",
    "partenariat": "partnership",
    "alliance": "alliance",
    "association": "association",
    "organisation": "organization",
    "institution": "institution",
    "entreprise": "company",
    "société": "society",
    "corporation": "corporation",
    "agence": "agency",
    "bureau": "office",
    "service": "service",
    "département": "department",
    "division": "division",
    "section": "section",
    "unité": "unit",
    "équipe": "team",
    "groupe": "group",
    "cellule": "cell",
    "comité": "committee",
    "commission": "commission",
    "conseil": "council",
    "assemblée": "assembly",
    "réunion": "meeting",
    "session": "session",
    "conférence": "conference",
    "séminaire": "seminar",
    "atelier": "workshop",
    "formation": "training",
    "stage": "internship",
    "apprentissage": "apprenticeship",
    "éducation": "education",
    "enseignement": "teaching",
    "pédagogie": "pedagogy",
    "didactique": "didactics",
    "méthodologie": "methodology",
    "approche": "approach",
    "technique": "technique",
    "procédé": "process",
    "méthode": "method",
    "stratégie": "strategy",
    "tactique": "tactic",
    "plan": "plan",
    "programme": "program",
    "projet": "project",
    "initiative": "initiative",
    "campagne": "campaign",
    "opération": "operation",
    "action": "action",
    "activité": "activity",
    "tâche": "task",
    "mission": "mission",
    "mandat": "mandate",
    "objectif": "objective",
    "but": "goal",
    "cible": "target",
    "finalité": "purpose",
    "raison d'être": "raison d'être",
    "motivation": "motivation",
    "inspiration": "inspiration",
    "créativité": "creativity",
    "innovation": "innovation",
    "invention": "invention",
    "découverte": "discovery",
    "exploration": "exploration",
    "aventure": "adventure",
    "expérience": "experience",
    "pratique": "practice",
    "application": "application",
    "utilisation": "use",
    "emploi": "use",
    "usage": "usage",
    "fonctionnement": "functioning",
    "opération": "operation",
    "processus": "process",
    "procédure": "procedure",
    "protocole": "protocol",
    "règlement": "regulation",
    "directive": "directive",
    "instruction": "instruction",
    "consigne": "instruction",
    "recommandation": "recommendation",
    "suggestion": "suggestion",
    "conseil": "advice",
    "orientation": "orientation",
    "guidage": "guidance",
    "assistance": "assistance",
    "aide": "help",
    "support": "support",
    "soutien": "support",
    "encouragement": "encouragement",
    "motivation": "motivation",
    "stimulation": "stimulation",
    "incitation": "incentive",
    "incitation": "incentive",
    "Commencez par ajouter votre premier pays.": "Start by adding your first country.",
    "Le pays a été créé avec succès!": "The country has been successfully created!",
    "Le pays a été mis à jour avec succès!": "The country has been successfully updated!",
    "Le pays a été supprimé avec succès!": "The country has been successfully deleted!",
    "Une erreur est survenue": "An error occurred",
    "Veuillez réessayer": "Please try again",
    "Chargement": "Loading",
    "Traitement en cours": "Processing in progress",
    "Opération réussie": "Operation successful",
    "Données enregistrées": "Data saved",
    "Modifications appliquées": "Changes applied",
    "Filtres appliqués": "Filters applied",
    "Résultats mis à jour": "Results updated",
    "Aucun enregistrement trouvé": "No record found",
    "Aucune donnée disponible": "No data available",
    "Veuillez sélectionner": "Please select",
    "Champ obligatoire": "Required field",
    "Format invalide": "Invalid format",
    "Valeur incorrecte": "Incorrect value",
    "Limite dépassée": "Limit exceeded",
    "Accès refusé": "Access denied",
    "Permission requise": "Permission required",
    "Session expirée": "Session expired",
    "Veuillez vous reconnecter": "Please log in again",
    "Identifiants incorrects": "Incorrect credentials",
    "Compte non trouvé": "Account not found",
    "Compte désactivé": "Account disabled",
    "Email déjà utilisé": "Email already used",
    "Mot de passe trop court": "Password too short",
    "Mot de passe incorrect": "Incorrect password",
    "Veuillez confirmer": "Please confirm",
    "Les mots de passe ne correspondent pas": "Passwords do not match",
    "Email envoyé": "Email sent",
    "Notification envoyée": "Notification sent",
    "Message reçu": "Message received",
    "Fichier téléchargé": "File downloaded",
    "Fichier téléversé": "File uploaded",
    "Importation réussie": "Import successful",
    "Exportation réussie": "Export successful",
    "Synchronisation terminée": "Synchronization completed",
    "Mise à jour disponible": "Update available",
    "Version actuelle": "Current version",
    "Dernière version": "Latest version",
    "Nouveautés": "What's new",
    "Améliorations": "Improvements",
    "Corrections de bugs": "Bug fixes",
    "Sécurité renforcée": "Enhanced security",
    "Performance optimisée": "Optimized performance",
    "Interface améliorée": "Improved interface",
    "Nouvelles fonctionnalités": "New features",
    "Fonctionnalités modifiées": "Modified features",
    "Fonctionnalités supprimées": "Removed features",
    "Compatibilité": "Compatibility",
    "Configuration requise": "Required configuration",
    "Installation": "Installation",
    "Désinstallation": "Uninstallation",
    "Redémarrage requis": "Restart required",
    "Veuillez redémarrer": "Please restart",
    "Sauvegarde automatique": "Automatic backup",
    "Restauration automatique": "Automatic restoration",
    "Nettoyage terminé": "Cleanup completed",
    "Maintenance en cours": "Maintenance in progress",
    "Service indisponible": "Service unavailable",
    "Veuillez revenir plus tard": "Please come back later",
    "Merci de votre patience": "Thank you for your patience",
    "Nous apprécions votre compréhension": "We appreciate your understanding",
    "Contactez le support": "Contact support",
    "Assistance technique": "Technical assistance",
    "Centre d'aide": "Help center",
    "Documentation": "Documentation",
    "FAQ": "FAQ",
    "Tutoriels": "Tutorials",
    "Guides": "Guides",
    "Base de connaissances": "Knowledge base",
    "Forum": "Forum",
    "Communauté": "Community",
    "Blog": "Blog",
    "Actualités": "News",
    "Événements": "Events",
    "Webinaires": "Webinars",
    "Formations": "Training",
    "Certifications": "Certifications",
    "Ressources": "Resources",
    "Outils": "Tools",
    "Services": "Services",
    "Solutions": "Solutions",
    "Produits": "Products",
    "Tarifs": "Pricing",
    "Plans": "Plans",
    "Options": "Options",
    "Personnalisation": "Customization",
    "Intégrations": "Integrations",
    "API": "API",
    "Développeurs": "Developers",
    "Partenaires": "Partners",
    "Clients": "Customers",
    "Témoignages": "Testimonials",
    "Études de cas": "Case studies",
    "Portfolio": "Portfolio",
    "Réalisations": "Achievements",
    "Expérience": "Experience",
    "Expertise": "Expertise",
    "Compétences": "Skills",
    "Services": "Services",
    "Solutions": "Solutions",
    "Innovation": "Innovation",
    "Qualité": "Quality",
    "Excellence": "Excellence",
    "Engagement": "Commitment",
    "Fiabilité": "Reliability",
    "Confiance": "Trust",
    "Transparence": "Transparency",
    "Éthique": "Ethics",
    "Valeurs": "Values",
    "Mission": "Mission",
    "Vision": "Vision",
    "Culture": "Culture",
    "Équipe": "Team",
    "Carrières": "Careers",
    "Recrutement": "Recruitment",
    "Stages": "Internships",
    "Alternance": "Work-study",
    "Formation": "Training",
    "Développement": "Development",
    "Évolution": "Evolution",
    "Opportunités": "Opportunities",
    "Défis": "Challenges",
    "Projets": "Projects",
    "Collaboration": "Collaboration",
    "Innovation": "Innovation",
    "Créativité": "Creativity",
    "Passion": "Passion",
    "Inspiration": "Inspiration",
    "Motivation": "Motivation",
    "Ambition": "Ambition",
    "Objectifs": "Objectives",
    "Résultats": "Results",
    "Performance": "Performance",
    "Efficacité": "Efficiency",
    "Productivité": "Productivity",
    "Optimisation": "Optimization",
    "Amélioration": "Improvement",
    "Progrès": "Progress",
    "Succès": "Success",
    "Réussite": "Achievement",
    "Excellence": "Excellence",
    "Qualité": "Quality",
    "Standards": "Standards",
    "Normes": "Standards",
    "Certifications": "Certifications",
    "Accréditations": "Accreditations",
    "Reconnaissance": "Recognition",
    "Distinctions": "Distinctions",
    "Récompenses": "Awards",
    "Honneurs": "Honors",
    "Mentions": "Mentions",
    "Publications": "Publications",
    "Recherches": "Research",
    "Études": "Studies",
    "Analyses": "Analyses",
    "Rapports": "Reports",
    "Statistiques": "Statistics",
    "Données": "Data",
    "Informations": "Information",
    "Métriques": "Metrics",
    "Indicateurs": "Indicators",
    "KPI": "KPI",
    "Tableaux de bord": "Dashboards",
    "Rapports": "Reports",
    "Analytiques": "Analytics",
    "Suivi": "Tracking",
    "Monitoring": "Monitoring",
    "Alertes": "Alerts",
    "Notifications": "Notifications",
    "Rappels": "Reminders",
    "Échéances": "Deadlines",
    "Planning": "Planning",
    "Calendrier": "Calendar",
    "Agenda": "Agenda",
    "Rendez-vous": "Appointments",
    "Réunions": "Meetings",
    "Présentations": "Presentations",
    "Démonstrations": "Demonstrations",
    "Formations": "Training",
    "Ateliers": "Workshops",
    "Séminaires": "Seminars",
    "Conférences": "Conferences",
    "Événements": "Events",
    "Réseautage": "Networking",
    "Collaboration": "Collaboration",
    "Partenariat": "Partnership",
    "Alliance": "Alliance",
    "Coopération": "Cooperation",
    "Synergie": "Synergy",
    "Intégration": "Integration",
    "Connexion": "Connection",
    "Lien": "Link",
    "Relation": "Relationship",
    "Interaction": "Interaction",
    "Communication": "Communication",
    "Échange": "Exchange",
    "Partage": "Sharing",
    "Transmission": "Transmission",
    "Réception": "Reception",
    "Envoi": "Sending",
    "Distribution": "Distribution",
    "Livraison": "Delivery",
    "Transport": "Transport",
    "Logistique": "Logistics",
    "Entreposage": "Storage",
    "Gestion": "Management",
    "Administration": "Administration",
    "Direction": "Management",
    "Leadership": "Leadership",
    "Autorité": "Authority",
    "Pouvoir": "Power",
    "Influence": "Influence",
    "Contrôle": "Control",
    "Supervision": "Supervision",
    "Surveillance": "Monitoring",
    "Inspection": "Inspection",
    "Vérification": "Verification",
    "Validation": "Validation",
    "Certification": "Certification",
    "Qualification": "Qualification",
    "Habilitation": "Authorization",
    "Compétence": "Competence",
    "Aptitude": "Aptitude",
    "Capacité": "Capacity",
    "Habileté": "Skill",
    "Talent": "Talent",
    "Don": "Gift",
    "Faculté": "Faculty",
    "Potential": "Potential",
    "Possibilité": "Possibility",
    "Opportunité": "Opportunity",
    "Option": "Option",
    "Alternative": "Alternative",
    "Choix": "Choice",
    "Sélection": "Selection",
    "Décision": "Decision",
    "Détermination": "Determination",
    "Résolution": "Resolution",
    "Solution": "Solution",
    "Réponse": "Answer",
    "Réplique": "Reply",
    "Retour": "Return",
    "Feedback": "Feedback",
    "Commentaire": "Comment",
    "Avis": "Opinion",
    "Critique": "Review",
    "Évaluation": "Evaluation",
    "Appréciation": "Appreciation",
    "Jugement": "Judgment",
    "Analyse": "Analysis",
    "Examen": "Examination",
    "Étude": "Study",
    "Recherche": "Research",
    "Investigation": "Investigation",
    "Enquête": "Survey",
    "Sondage": "Poll",
    "Consultation": "Consultation",
    "Entretien": "Interview",
    "Discussion": "Discussion",
    "Débat": "Debate",
    "Dialogue": "Dialogue",
    "Conversation": "Conversation",
    "Échange": "Exchange",
    "Communication": "Communication",
    "Transmission": "Transmission",
    "Diffusion": "Broadcasting",
    "Distribution": "Distribution",
    "Partage": "Sharing",
    "Collaboration": "Collaboration",
    "Coopération": "Cooperation",
    "Partenariat": "Partnership",
    "Alliance": "Alliance",
    "Association": "Association",
    "Organisation": "Organization",
    "Institution": "Institution",
    "Entreprise": "Company",
    "Société": "Society",
    "Corporation": "Corporation",
    "Agence": "Agency",
    "Bureau": "Office",
    "Service": "Service",
    "Département": "Department",
    "Division": "Division",
    "Section": "Section",
    "Unité": "Unit",
    "Équipe": "Team",
    "Groupe": "Group",
    "Cellule": "Cell",
    "Comité": "Committee",
    "Commission": "Commission",
    "Conseil": "Council",
    "Assemblée": "Assembly",
    "Réunion": "Meeting",
    "Session": "Session",
    "Conférence": "Conference",
    "Séminaire": "Seminar",
    "Atelier": "Workshop",
    "Formation": "Training",
    "Stage": "Internship",
    "Apprentissage": "Apprenticeship",
    "Éducation": "Education",
    "Enseignement": "Teaching",
    "Pédagogie": "Pedagogy",
    "Didactique": "Didactics",
    "Méthodologie": "Methodology",
    "Approche": "Approach",
    "Technique": "Technique",
    "Procédé": "Process",
    "Méthode": "Method",
    "Stratégie": "Strategy",
    "Tactique": "Tactic",
    "Plan": "Plan",
    "Programme": "Program",
    "Projet": "Project",
    "Initiative": "Initiative",
    "Campagne": "Campaign",
    "Opération": "Operation",
    "Action": "Action",
    "Activité": "Activity",
    "Tâche": "Task",
    "Mission": "Mission",
    "Mandat": "Mandate",
    "Objectif": "Objective",
    "But": "Goal",
    "Cible": "Target",
    "Finalité": "Purpose",
    "Raison d'être": "Raison d'être",
    "Motivation": "Motivation",
    "Inspiration": "Inspiration",
    "Créativité": "Creativity",
    "Innovation": "Innovation",
    "Invention": "Invention",
    "Découverte": "Discovery",
    "Exploration": "Exploration",
    "Aventure": "Adventure",
    "Expérience": "Experience",
    "Pratique": "Practice",
    "Application": "Application",
    "Utilisation": "Use",
    "Emploi": "Use",
    "Usage": "Usage",
    "Fonctionnement": "Functioning",
    "Opération": "Operation",
    "Processus": "Process",
    "Procédure": "Procedure",
    "Protocole": "Protocol",
    "Règlement": "Regulation",
    "Directive": "Directive",
    "Instruction": "Instruction",
    "Consigne": "Instruction",
    "Recommandation": "Recommendation",
    "Suggestion": "Suggestion",
    "Conseil": "Advice",
    "Orientation": "Orientation",
    "Guidage": "Guidance",
    "Assistance": "Assistance",
    "Aide": "Help",
    "Support": "Support",
    "Soutien": "Support",
    "Encouragement": "Encouragement",
    "Motivation": "Motivation",
    "Stimulation": "Stimulation",
    "Incitation": "Incentive",
}

def translate_po_file(file_path):
    """Translate all French strings in a PO file to English"""
    
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Pattern to match msgid and msgstr pairs
    pattern = r'(msgid\s+"([^"]*)"\s*\nmsgstr\s+")([^"]*)(")'
    
    def replace_match(match):
        msgid_full = match.group(1)
        msgid_text = match.group(2)
        msgstr_start = match.group(3)
        msgstr_end = match.group(4)
        
        # Skip if msgid is empty (header)
        if not msgid_text:
            return msgid_full + msgstr_start + msgstr_end
        
        # Look up translation in our dictionary
        translation = TRANSLATIONS.get(msgid_text, "")
        
        # If no translation found, try to provide a basic one
        if not translation:
            # Simple heuristic: if it's a short phrase, keep it as is
            # For longer phrases, provide a basic translation
            if len(msgid_text) > 20:
                translation = msgid_text  # Keep original for complex strings
            else:
                translation = msgid_text  # Keep original for all
        
        return msgid_full + msgstr_start + translation + msgstr_end
    
    # Apply translations
    translated_content = re.sub(pattern, replace_match, content, flags=re.MULTILINE)
    
    # Write the translated content back
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(translated_content)
    
    print(f"Translation completed for {file_path}")

if __name__ == "__main__":
    file_path = "c:\\Users\\LENOVO\\Desktop\\PROJET\\Sourcing\\locale\\en\\LC_MESSAGES\\django copy.po"
    translate_po_file(file_path)
