# Generated by Django 4.2.25 on 2026-01-07 16:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeCotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom_client', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=50)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_conditionnement', models.CharField(choices=[('VRAC', 'Vrac'), ('FLEXITANK', 'Flexitank'), ('ISOTANK', 'Isotank'), ('AUTRE', 'Autre')], default='CONTENEUR', max_length=20)),
                ('incoterm', models.CharField(choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CIF', 'CIF'), ('CFR', 'CFR')], default='FOB', max_length=10)),
                ('pol', models.CharField(blank=True, max_length=255, verbose_name='Port de chargement (POL)')),
                ('pod', models.CharField(blank=True, max_length=255, verbose_name='Port de déchargement (POD)')),
                ('target_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('commodite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodites.commodite')),
            ],
            options={
                'verbose_name': 'Demande de cotation',
                'verbose_name_plural': 'Demandes de cotation',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='EmailQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('CLIENT_CONFIRMATION', 'Confirmation client'), ('ADMIN_NOTIFICATION', 'Notification admin')], max_length=50)),
                ('to_email', models.EmailField(max_length=254)),
                ('cc_emails', models.TextField(blank=True, help_text='Emails en copie, séparés par des virgules')),
                ('subject', models.CharField(max_length=255)),
                ('html_content', models.TextField()),
                ('text_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cotation.demandecotation')),
            ],
            options={
                'verbose_name': 'Email en attente',
                'verbose_name_plural': 'Emails en attente',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sent', 'created_at'], name='cotation_em_sent_891263_idx'), models.Index(fields=['demande'], name='cotation_em_demande_9fbfa0_idx')],
            },
        ),
    ]
