# Generated by Django 4.2.25 on 2026-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandecotation',
            name='target_price_currency',
            field=models.CharField(choices=[('XOF', 'XOF (Francs CFA)'), ('USD', 'USD (Dollars)'), ('EUR', 'EUR (Euros)'), ('GBP', 'GBP (Livres sterling)'), ('CHF', 'CHF (Francs suisses)')], default='XOF', max_length=3),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='pol',
            field=models.CharField(blank=True, choices=[('ABIDJ', 'Abidjan'), ('SAN', 'San Pedro')], max_length=255, verbose_name='Port de chargement (POL)'),
        ),
    ]
