# Generated by Django 4.2.25 on 2026-01-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotation', '0002_demandecotation_target_price_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecotation',
            name='target_price_currency',
            field=models.CharField(choices=[('XOF', 'XOF (Francs CFA)'), ('USD', 'USD (Dollars)'), ('EUR', 'EUR (Euros)'), ('GBP', 'GBP (Livres sterling)'), ('CHF', 'CHF (Francs suisses)')], max_length=3),
        ),
    ]
