# Generated by Django 4.2.25 on 2026-02-03 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commodites', '0002_alter_commodite_couleur_and_more'),
        ('cotation', '0003_alter_demandecotation_target_price_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandecotation',
            name='commodite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commodites.commodite', verbose_name='Commodité'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='contact',
            field=models.CharField(max_length=50, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='incoterm',
            field=models.CharField(choices=[('EXW', 'EXW'), ('FOB', 'FOB'), ('CIF', 'CIF'), ('CFR', 'CFR')], default='FOB', max_length=10, verbose_name='Incoterm'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='nom_client',
            field=models.CharField(max_length=255, verbose_name='Nom client'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='pod',
            field=models.CharField(max_length=255, verbose_name='Port de déchargement (POD)'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='pol',
            field=models.CharField(choices=[('ABIDJ', 'Abidjan'), ('SAN', 'San Pedro')], max_length=255, verbose_name='Port de chargement (POL)'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='quantite',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TRAITEE', 'Traitée'), ('REFUSEE', 'Refusée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='target_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix cible'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='target_price_currency',
            field=models.CharField(choices=[('XOF', 'XOF (Francs CFA)'), ('USD', 'USD (Dollars)'), ('EUR', 'EUR (Euros)'), ('GBP', 'GBP (Livres sterling)'), ('CHF', 'CHF (Francs suisses)')], max_length=3, verbose_name='Devise du prix cible'),
        ),
        migrations.AlterField(
            model_name='demandecotation',
            name='type_conditionnement',
            field=models.CharField(choices=[('VRAC', 'Vrac'), ('FLEXITANK', 'Flexitank'), ('ISOTANK', 'Isotank'), ('AUTRE', 'Autre')], default='CONTENEUR', max_length=20, verbose_name='Type de conditionnement'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='attempts',
            field=models.IntegerField(default=0, verbose_name='Tentatives'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='cotation.demandecotation', verbose_name='Demande'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='email_type',
            field=models.CharField(choices=[('CLIENT_CONFIRMATION', 'Confirmation client'), ('ADMIN_NOTIFICATION', 'Notification admin')], max_length=50, verbose_name="Type d'email"),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='error_message',
            field=models.TextField(blank=True, verbose_name="Message d'erreur"),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='html_content',
            field=models.TextField(verbose_name='Contenu HTML'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Envoyé'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi"),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Sujet'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='text_content',
            field=models.TextField(blank=True, verbose_name='Contenu texte'),
        ),
        migrations.AlterField(
            model_name='emailqueue',
            name='to_email',
            field=models.EmailField(max_length=254, verbose_name='Email destinataire'),
        ),
    ]
