# Generated by Django 4.2.25 on 2025-10-17 22:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commodites", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Echantionnage",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        editable=False,
                        help_text="Référence unique de l'échantillon",
                        max_length=50,
                        unique=True,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantité échantillonnée (tonne)",
                        max_digits=12,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix d'achat ou de vente selon la relation",
                        max_digits=12,
                        null=True,
                        verbose_name="Prix en FCFA",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date à laquelle l'échantillon a été prélevé",
                        verbose_name="Date de création de l'échantillon",
                    ),
                ),
                (
                    "taux_acidite_ffa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Taux d'acides gras libres (Free Fatty Acid) en pourcentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux d'acidité (FFA %)",
                    ),
                ),
                (
                    "impurete_insolubles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pourcentage d'impuretés insolubles",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Impuretés insolubles (%)",
                    ),
                ),
                (
                    "teneur_eau_matiere_volatiles_mnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Teneur en eau et matières volatiles (Moisture and Not Lipid) en pourcentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Teneur en eau et matières volatiles (MNL %)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'enregistrement"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Échantillonnage",
                "verbose_name_plural": "Échantillonnages",
                "db_table": "echantionnage",
                "ordering": ["-date_creation"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEchantionnage",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        help_text="Référence unique de l'échantillon",
                        max_length=50,
                        verbose_name="Référence",
                    ),
                ),
                (
                    "quantite",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Quantité échantillonnée (tonne)",
                        max_digits=12,
                        verbose_name="Quantité",
                    ),
                ),
                (
                    "prix",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix d'achat ou de vente selon la relation",
                        max_digits=12,
                        null=True,
                        verbose_name="Prix en FCFA",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date à laquelle l'échantillon a été prélevé",
                        verbose_name="Date de création de l'échantillon",
                    ),
                ),
                (
                    "taux_acidite_ffa",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Taux d'acides gras libres (Free Fatty Acid) en pourcentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Taux d'acidité (FFA %)",
                    ),
                ),
                (
                    "impurete_insolubles",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pourcentage d'impuretés insolubles",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Impuretés insolubles (%)",
                    ),
                ),
                (
                    "teneur_eau_matiere_volatiles_mnl",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Teneur en eau et matières volatiles (Moisture and Not Lipid) en pourcentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Teneur en eau et matières volatiles (MNL %)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date d'enregistrement"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "commodite",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Commodité échantillonnée",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="commodites.commodite",
                        verbose_name="Commodité",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Échantillonnage",
                "verbose_name_plural": "historical Échantillonnages",
                "db_table": "echantionnage_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
