# Generated by Django 4.2.25 on 2026-01-07 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('echantillonnages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='echantionnage',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date à laquelle l'enregistrement a été créé", verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='echantionnage',
            name='quantite',
            field=models.DecimalField(decimal_places=2, help_text='Quantité (tonne)', max_digits=12, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='historicalechantionnage',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="Date à laquelle l'enregistrement a été créé", verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='historicalechantionnage',
            name='quantite',
            field=models.DecimalField(decimal_places=2, help_text='Quantité (tonne)', max_digits=12, verbose_name='Quantité'),
        ),
    ]
