# Generated by Django 4.2.25 on 2025-10-17 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commodites", "0001_initial"),
        ("utilisateur", "0001_initial"),
        ("echantillonnages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalechantionnage",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Agent ayant effectué l'échantillonnage",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="utilisateur.utilisateur",
                verbose_name="Agent",
            ),
        ),
        migrations.AddField(
            model_name="echantionnage",
            name="commodite",
            field=models.ForeignKey(
                help_text="Commodité échantillonnée",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="echantillonnages",
                to="commodites.commodite",
                verbose_name="Commodité",
            ),
        ),
        migrations.AddField(
            model_name="echantionnage",
            name="utilisateur",
            field=models.ForeignKey(
                help_text="Agent ayant effectué l'échantillonnage",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="echantillonnages",
                to="utilisateur.utilisateur",
                verbose_name="Agent",
            ),
        ),
        migrations.AddIndex(
            model_name="echantionnage",
            index=models.Index(
                fields=["reference"], name="echantionna_referen_17265e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="echantionnage",
            index=models.Index(
                fields=["date_creation"], name="echantionna_date_cr_82dbc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="echantionnage",
            index=models.Index(
                fields=["utilisateur"], name="echantionna_utilisa_797596_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="echantionnage",
            index=models.Index(
                fields=["commodite"], name="echantionna_commodi_1fcfaa_idx"
            ),
        ),
    ]
