# Generated by Django 4.2.25 on 2025-12-15 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
    ]
