# Generated by Django 4.2.25 on 2025-12-18 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import fournisseurs.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom du fournisseur')),
                ('nom_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du responsable')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude ')),
                ('contact', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact')),
                ('document_fourni_aex', models.FileField(blank=True, help_text='Documents administratifs du fournisseur', null=True, upload_to=fournisseurs.models.upload_to_fournisseur_documents, verbose_name='Document fourni (AEX)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('localite', models.ForeignKey(blank=True, help_text='Localité précise du fournisseur', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='villes.localite', verbose_name='Localité')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fournisseur_profile', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur associé')),
                ('ville', models.ForeignKey(help_text='Ville où se trouve le fournisseur', on_delete=django.db.models.deletion.PROTECT, related_name='fournisseurs', to='villes.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'db_table': 'fournisseur',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalFournisseur',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, verbose_name='Identifiant unique')),
                ('nom', models.CharField(db_index=True, max_length=150, verbose_name='Nom du fournisseur')),
                ('nom_responsable', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nom du responsable')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude ')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude ')),
                ('contact', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Contact')),
                ('document_fourni_aex', models.TextField(blank=True, help_text='Documents administratifs du fournisseur', max_length=100, null=True, verbose_name='Document fourni (AEX)')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Date de mise à jour')),
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('localite', models.ForeignKey(blank=True, db_constraint=False, help_text='Localité précise du fournisseur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='villes.localite', verbose_name='Localité')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Compte utilisateur associé')),
                ('ville', models.ForeignKey(blank=True, db_constraint=False, help_text='Ville où se trouve le fournisseur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='villes.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name': 'historical Fournisseur',
                'verbose_name_plural': 'historical Fournisseurs',
                'db_table': 'fournisseur_history',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FournisseurPort',
            fields=[
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text='Distance entre le port et le fournisseur', max_digits=15, null=True, verbose_name='Distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_fournisseurs', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_ports', to='port.port', verbose_name='Port')),
            ],
            options={
                'verbose_name': 'Lien Fournisseur-Port',
                'verbose_name_plural': 'Liens Fournisseur-Ports',
                'db_table': 'fournisseur_port',
                'indexes': [models.Index(fields=['fournisseur'], name='fournisseur_fournis_8705e3_idx'), models.Index(fields=['port'], name='fournisseur_port_id_30519b_idx')],
                'unique_together': {('fournisseur', 'port')},
            },
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['nom'], name='fournisseur_nom_29e4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='fournisseur',
            index=models.Index(fields=['ville'], name='fournisseur_ville_i_c98fb3_idx'),
        ),
    ]
