# Generated by Django 4.2.25 on 2025-10-27 11:12

import django.core.validators
from django.db import migrations, models
import fournisseurs.models
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Nom du fournisseur"
                    ),
                ),
                (
                    "nom_responsable",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nom du responsable",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude "),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude "),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Contact",
                    ),
                ),
                (
                    "distance_port_abidjan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance du port d'Abidjan",
                    ),
                ),
                (
                    "distance_port_sanpedro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance du port de San-Pedro",
                    ),
                ),
                (
                    "document_fourni_aex",
                    models.FileField(
                        blank=True,
                        help_text="Documents administratifs du fournisseur",
                        null=True,
                        upload_to=fournisseurs.models.upload_to_fournisseur_documents,
                        verbose_name="Document fourni (AEX)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "fournisseur",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFournisseur",
            fields=[
                (
                    "deleted",
                    models.DateTimeField(db_index=True, editable=False, null=True),
                ),
                (
                    "deleted_by_cascade",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        verbose_name="Identifiant unique",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Nom du fournisseur"
                    ),
                ),
                (
                    "nom_responsable",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Nom du responsable",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude "),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude "),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Contact",
                    ),
                ),
                (
                    "distance_port_abidjan",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance du port d'Abidjan",
                    ),
                ),
                (
                    "distance_port_sanpedro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distance du port de San-Pedro",
                    ),
                ),
                (
                    "document_fourni_aex",
                    models.TextField(
                        blank=True,
                        help_text="Documents administratifs du fournisseur",
                        max_length=100,
                        null=True,
                        verbose_name="Document fourni (AEX)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Fournisseur",
                "verbose_name_plural": "historical Fournisseurs",
                "db_table": "fournisseur_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
