# Generated by Django 4.2.25 on 2025-11-03 14:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fournisseurs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("villes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalfournisseur",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalfournisseur",
            name="localite",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Localité précise du fournisseur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="villes.localite",
                verbose_name="Localité",
            ),
        ),
        migrations.AddField(
            model_name="historicalfournisseur",
            name="ville",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Ville où se trouve le fournisseur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="villes.ville",
                verbose_name="Ville",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="localite",
            field=models.ForeignKey(
                blank=True,
                help_text="Localité précise du fournisseur",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fournisseurs",
                to="villes.localite",
                verbose_name="Localité",
            ),
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="ville",
            field=models.ForeignKey(
                help_text="Ville où se trouve le fournisseur",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fournisseurs",
                to="villes.ville",
                verbose_name="Ville",
            ),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(fields=["nom"], name="fournisseur_nom_29e4aa_idx"),
        ),
        migrations.AddIndex(
            model_name="fournisseur",
            index=models.Index(fields=["ville"], name="fournisseur_ville_i_c98fb3_idx"),
        ),
    ]
