# Generated by Django 4.2.25 on 2025-11-04 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Pays", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpays",
            name="flag",
            field=models.TextField(
                blank=True,
                help_text="Drapeau du pays",
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Drapeau du pays",
            ),
        ),
        migrations.AddField(
            model_name="pays",
            name="flag",
            field=models.ImageField(
                blank=True,
                help_text="Drapeau du pays",
                null=True,
                upload_to="flags",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Drapeau du pays",
            ),
        ),
    ]
