"""
Django settings for Sourcing project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from django.contrib.messages import constants as messages
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from django.utils.translation import gettext_lazy as _

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-%$=ojq4m%lt$vxt16%9fu@vsah&t&fhy5u6m=*9(u^q#2dqvil"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "odmuk51kvk9p.share.zrok.io",  # ton domaine zrok
]


# DEBUG = False

# ALLOWED_HOSTS = ['sourcing.empotage-oils-of-africa.net']


# Application definition

INSTALLED_APPS = [
    # Applications internes
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Applications du projet
    'utilisateur',
    'fournisseurs',
    'villes',
    'zones',
    'commodites',
    'echantillonnages',
    'Pays',
    'port',
    'website',
    'cotation',

    # Applications tierces
    'crispy_bootstrap5',
    'crispy_forms',
    'safedelete',
    'corsheaders',
    'simple_history',
    'widget_tweaks',
    "colorfield",

    # Authentification
    'django_otp',
    'django_otp.plugins.otp_static',
    'django_otp.plugins.otp_totp',
    'two_factor',
]

# ============================================================================
# CONFIGURATION AUTH_USER_MODEL
# ============================================================================
# TRÈS IMPORTANT : Définir avant la première migration !
AUTH_USER_MODEL = 'utilisateur.Utilisateur'


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "Sourcing.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'utilisateur/templates'),
            os.path.join(BASE_DIR, 'fournisseurs/templates'),
            os.path.join(BASE_DIR, 'villes/templates'),
            os.path.join(BASE_DIR, 'zones/templates'),
            os.path.join(BASE_DIR, 'commodites/templates'),
            os.path.join(BASE_DIR, 'echantillonnages/templates'),
            os.path.join(BASE_DIR, 'website/templates'),
            os.path.join(BASE_DIR, 'cotation/templates'),           
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "Sourcing.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sourcing',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',  # Essayez 'localhost' au lieu de '127.0.0.1'
        'PORT': '5432',
        'OPTIONS': {
            'client_encoding': 'UTF8',
        },
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'
LANGUAGES = [
    ('fr', _('francais')),
    ('en', _('English')),
]



LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)
TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'  # URL pour accéder aux fichiers statiques

# Emplacement des fichiers statiques dans le projet
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Dossier où Django stockera les fichiers téléchargés
MEDIA_URL = 'medias/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'medias')

# Configuration Mapbox
MAPBOX_ACCESS_TOKEN = 'pk.eyJ1IjoiaWJyYWsiLCJhIjoiY21oYnV4M3M5MDZqMTJyc2E0enFpbTlwaCJ9.OH_RYh--XO3vn363pKRlRg'


# Dossier où Django collectera tous les fichiers statiques lors de la mise en production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



# smtp
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'empotageoilsofafrica@gmail.com'  # Replace with your Gmail address
EMAIL_HOST_PASSWORD = 'vlym rhmk nmht rhge'
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}


SITE_NAME = 'Sourcing Platform'






# settings.py

CSRF_TRUSTED_ORIGINS = [
    "https://127.0.0.1:8000",  # si tu veux tester en local
    "https://odmuk51kvk9p.share.zrok.io",  # l'URL publique générée par zrok
]
