# Generated by Django 4.2.25 on 2025-12-15 21:07

import random
import uuid

from django.db import migrations, models
import django.db.models.deletion
from django.utils.translation import gettext_lazy as _


def generate_random_color():
    """Génère une couleur aléatoire au format hexadécimal (#RRGGBB)"""
    return '#{:02x}{:02x}{:02x}'.format(
        random.randint(0, 255),
        random.randint(0, 255),
        random.randint(0, 255)
    )


def set_default_colors(apps, schema_editor):
    Commodite = apps.get_model('commodites', 'Commodite')
    for commodite in Commodite.objects.all():
        if not hasattr(commodite, 'couleur') or not commodite.couleur or commodite.couleur == '#000000':
            commodite.couleur = generate_random_color()
            commodite.save(update_fields=['couleur'])


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('fournisseurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant unique')),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('nom', models.CharField(help_text='Type de produit agricole (ex: Cacao, Café, Noix de cajou, etc.)', max_length=150, verbose_name='Nom de la commodité')),
                ('couleur', models.CharField(default='#000000', help_text="Couleur pour l'affichage sur la carte (format hexadécimal)", max_length=7, verbose_name='Couleur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Commodité',
                'verbose_name_plural': 'Commodités',
                'ordering': ['nom'],
                'db_table': 'commodite',
            },
        ),
        migrations.CreateModel(
            name='FournisseurCommodite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted', models.DateTimeField(db_index=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commodite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_fournisseurs', to='commodites.commodite', verbose_name='Commodité')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_commodites', to='fournisseurs.fournisseur', verbose_name='Fournisseur')),
            ],
            options={
                'db_table': 'fournisseur_commodite',
                'verbose_name': 'Lien Fournisseur-Commodité',
                'verbose_name_plural': 'Liens Fournisseur-Commodités',
                'unique_together': {('fournisseur', 'commodite')},
            },
        ),
        migrations.RunPython(
            code=set_default_colors,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
