# Generated by Django 4.2.25 on 2025-11-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Pays", "0003_historicalpays_flag_pays_flag"),
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalzone",
            name="pays",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Pays auquel appartient la zone",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="zone",
                to="Pays.pays",
                verbose_name="Pays",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="pays",
            field=models.ForeignKey(
                help_text="Pays auquel appartient la zone",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="zones",
                related_query_name="zone",
                to="Pays.pays",
                verbose_name="Pays",
            ),
        ),
    ]
